version: '3'
services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports: 
      - "6379:6379"
  mongo:
    image: mongo:3.7.9-jessie
    ports:
      - 27017:27017
  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
  jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9441
    image: jaegertracing/all-in-one:latest
    ports:
      - 14268:14268
      - 9411:9411
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
